[package]
name = "ch6_coin"
version = "0.1.0"
authors = ["Hidemaro Fujinami <guppy4.spurs21@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
